routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CommentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('posts');
});

Route::resource('posts', PostController::class);
Route::resource('comments', CommentController::class);

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable= ['title', 'user_name', 'description'];

    public function comments(){
        return $this->hasMany(Comment::class);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Validator;
use Illuminate\Http\Request;

class PostController extends Controller
{

    protected function _validation_rules($request, $id)
    {
        return [
            'user_name' => ['required'],
            'title'     =>  ["required"],
            'description' => ['required'],
        ];
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [];
        $data['posts'] = Post::all();
        return view('posts.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [];
        $data['posts']  = Post::all();
        $data['method']  = 'POST';
        $data['route']  = route('posts.store');
        return view('posts.partials.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validation = Validator::make($request->all(), 
        $this->_validation_rules($request, Null));
        if ($validation->fails())
        {
            return redirect('posts/create')
                        ->withErrors($validation)
                        ->withInput();
        }
        $model = new Post();
        $this->_save($model, $id);
        return redirect()->route('posts.index')
        ->with('success','Post created successfully');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = [];
        $data['model']  = Post::find($id);
        $data['posts']  = Post::all();
        $data['method']  = 'PATCH';
        $data['route']  = route('posts.update',$id);
        $data['id']     = $id;
        return view('posts.partials.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validation = Validator::make($request->all(), 
        $this->_validation_rules($request, $id));

        if ($validation->fails())
        {
            return redirect('posts/'.$id.'/edit')
                        ->withErrors($validation)
                        ->withInput();
        }
        $model = Post::find($id);
        $this->_save($model, $id);
        return redirect()->route('posts.index')
        ->with('success','Post Updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = Post::find($id);
        $model->delete();

        return redirect()->route('posts.index')
        ->with('success','Post Deleted successfully');
    }

    protected function _save($model,&$id){
        $data = request()->except('_token');
        $model->fill($data);
        $model->save();
    }
}

resources/views/posts/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="bg-light p-2 mt-2">
       <h3 class="text-center"> Hi Welcome!</h3>
        <h4><p class="text-right"> Total Posts - {{$posts->count()}} </p></h4></div>
        <div class="bg-light p-2 mt-2 text-right">
            <a href="{{route('posts.create')}}"><button class="btn btn-primary btn-sm shadow-none" type="button">Create Post</button></p></a>
        </div>
        @include('posts.show')
@endsection

resources/views/posts/show.blade.php
@foreach ($posts as $key => $post)
    <div class="d-flex flex-column comment-section" id="myGroup">
        <div class="bg-white p-2">
            <div class="d-flex flex-row user-info">
                <p data-letters="{{ucfirst(substr($post->user_name, 0, 1))}}"></p>
                <div class="d-flex flex-column justify-content-start ml-2">
                    <span class="d-block font-weight-bold name">{{$post->user_name}}</span>
                    <span class="date text-black-50">Shared publicly - {{$post->created_at->diffForHumans()}}</span></div>
                </div>
                <div class="d-flex flex-row align-items-start pull-right">
                    <a href="{{route('posts.edit', @$post->id)}}">
                        <button type="button" class="btn btn-info sm">
                            <i class="fa fa-edit"></i>
                        </button>
                    </a>&nbsp;&nbsp;
                    <form action="{{ route('posts.destroy',$post->id) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger sm">
                            <i class="fa fa-trash"></i>
                        </button>
                    </form>
                </div>

                <div class="mt-2">
                    <h5>{{$post->title}}</h5>
                    <p class="comment-text">{{$post->description}}</p>
                </div>
            </div>
            <div class="bg-white p-2">
                <div class="d-flex flex-row fs-12">
                    <div class="like p-2 cursor action-collapse" data-toggle="collapse" aria-expanded="true" aria-controls="collapse-{{$post->id}}" href="#collapse-{{$post->id}}">
                        <i class="fa fa-commenting-o"></i><span class="ml-1">Comment ({{$post->comments->count()}})</span></div>
                </div>
            </div>
        </div>  

    @include('comments.partials.form')

@endforeach
@if ($posts->count() == 0)
<div class="d-flex flex-column comment-section" id="myGroup">
    <div class="bg-white p-2 text-center">
    <h4>No Posts</h4>
    </div>
</div>
@endif