routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CommentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('posts');
});

Route::resource('posts', PostController::class);
Route::resource('comments', CommentController::class);

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Comment extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable= ['post_id', 'user_name', 'description'];

    public function post(){
        return $this->belongsTo(Post::class, 'post_id');
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Comment;
use App\Models\Post;
use Validator;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    protected function _validation_rules($request, $id)
    {
        return [
            'user_name' => ['required'],
            'description' => ['required'],
        ];
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validation = Validator::make($request->all(), 
        $this->_validation_rules($request, Null));
        if ($validation->fails())
        {
            return redirect('posts')
                        ->withErrors($validation)
                        ->withInput();
        }
        $model = new Comment();
        $this->_save($model, $id);
        return redirect()->route('posts.index')
        ->with('success','Comment created successfully');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $comment =  Comment::find($id);
        $method  = 'PATCH';
        $route  = route('comments.update',$id);
        return response()->json([
	      'data' => $comment,
          'route' => $route,
          'method' => $method
	    ]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $model = Comment::find($id);

        $validation = Validator::make($request->all(), 
        $this->_validation_rules($request, $id));

        if ($validation->fails())
        {
            return redirect('posts')
                        ->withErrors($validation)
                        ->withInput();
        }
        $model = Comment::find($id);
        $this->_save($model, $id);
        return redirect()->route('posts.index')
        ->with('success','Comment Updated successfully');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = Comment::find($id);
        $model->delete();

        return redirect()->route('posts.index')
        ->with('success','Comment Deleted successfully');
    }

    protected function _save($model,&$id){

        $data = request()->except('_token');
        $model->fill($data);
        $model->save();
    }
}

resources/views/comments/show.blade.php
@foreach ($post->comments as $key => $comment)
<div class="d-flex flex-column comment-section" id="myGroup">
    <div class="bg-white p-2">
        <div class="d-flex flex-row user-info">
            <p data-letters="{{ucfirst(substr($comment->user_name, 0, 1))}}"></p>
            <div class="d-flex flex-column justify-content-start ml-2">
                <span class="d-block font-weight-bold name">{{$comment->user_name}}</span>
                <span class="date text-black-50">Shared publicly - {{$comment->created_at->diffForHumans()}}</span></div>
            </div>
            <div class="d-flex flex-row align-items-start pull-right">
                <button type="button" data-route={{route('comments.edit', $comment['id'])}} data-id={{$comment['id']}} class="btn btn-info sm editButton" id="editButton-{{$comment['id']}}">
                    <i class="fa fa-edit"></i>
                </button>
                &nbsp;&nbsp;
                <form action="{{ route('comments.destroy',$comment->id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger sm">
                        <i class="fa fa-trash"></i>
                    </button>
                </form>
            </div>
            <div class="mt-2">
                <p class="comment-text">{{$comment->description}}</p>
            </div>
        </div>
    </div>
@endforeach 
</div>