routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CommentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('posts');
});

Route::resource('posts', PostController::class);
Route::resource('comments', CommentController::class);

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Comment extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable= ['post_id', 'user_name', 'description'];

    public function post(){
        return $this->belongsTo(Post::class, 'post_id');
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Comment;
use App\Models\Post;
use Validator;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    protected function _validation_rules($request, $id)
    {
        return [
            'user_name' => ['required'],
            'description' => ['required'],
        ];
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validation = Validator::make($request->all(), 
        $this->_validation_rules($request, Null));
        if ($validation->fails())
        {
            return redirect('posts')
                        ->withErrors($validation)
                        ->withInput();
        }
        $model = new Comment();
        $this->_save($model, $id);
        return redirect()->route('posts.index')
        ->with('success','Comment created successfully');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $comment =  Comment::find($id);
        $method  = 'PATCH';
        $route  = route('comments.update',$id);
        return response()->json([
	      'data' => $comment,
          'route' => $route,
          'method' => $method
	    ]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $model = Comment::find($id);

        $validation = Validator::make($request->all(), 
        $this->_validation_rules($request, $id));

        if ($validation->fails())
        {
            return redirect('posts')
                        ->withErrors($validation)
                        ->withInput();
        }
        $model = Comment::find($id);
        $this->_save($model, $id);
        return redirect()->route('posts.index')
        ->with('success','Comment Updated successfully');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = Comment::find($id);
        $model->delete();

        return redirect()->route('posts.index')
        ->with('success','Comment Deleted successfully');
    }

    protected function _save($model,&$id){

        $data = request()->except('_token');
        $model->fill($data);
        $model->save();
    }
}

resources/views/comments/partials/form.blade.php
<div id="collapse-{{$post->id}}" class="bg-light p-2 collapse" data-parent="#myGroup">
    <form class="commentForm" method="POST">
        {{ csrf_field() }}
        @if (@$model['id'])
            <input type="hidden" name="_method" value="PUT">
            <input name="id" type="hidden" value="{{@$model['id']}}" ></>
        @endif
        <input name="post_id" type="hidden" value="{{@$post['id']}}" ></>

            <div class="d-flex flex-row align-items-start mt-2">
                <input name="user_name" type="text" value="{{@$model['user_name']}}" id="user_name" class="form-control ml-1 shadow-none user_name" placeholder="Enter User Name"></>
            </div>
            <div class="d-flex flex-row align-items-start mt-2">
                <textarea name="description"  class="form-control ml-1 shadow-none description" id="description" placeholder="Enter Description">{{@$model['description']}}</textarea>
            </div>
            <div class="mt-2 text-right">
                <button class="btn btn-primary btn-sm shadow-none" type="submit">Post comment</button>
                <button class="btn btn-outline-primary btn-sm ml-1 shadow-none" type="button">Cancel</button>
            </div>
    </form>
<div class="d-flex flex-row align-items-start">
</div>
   @include('comments.show')

  @push('scripts')
  <script>
        $( document ).ready(function() {
            $(".commentForm").attr('action', "{{route('comments.store')}}");

          $('body').on('click', '.editButton', function(){
               var id = $(this).data('id');
               var Url = $(this).data('route');
               $.ajax({
            method: "GET",
            url: Url,
            data: { id: id }
            })
            .done(function( response ) {
                $('.commentForm').removeAttr('action')
                $("<input>").attr({
                name: "_method",
                id: "hiddenId",
                type: "hidden",
                value: 'PUT'
            }).appendTo(".commentForm");
                $(".commentForm").attr('action', response.route);
                $(".user_name").val(response.data.user_name);
                $(".description").val(response.data.description);
            });
          });
    //       var id = '1';
    //     
      });
  </script>
  @endpush 